name = "ClimFlowsTestCases"
uuid = "55a4ed1b-ebae-44a5-bd1f-98d158431b8a"
authors = ["The ClimFlows contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
